// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf15Z73SJ59fiPbfoP3SYUeiINwYr5dWY',
    appId: '1:267960292278:web:d5b462b340760c6c35a717',
    messagingSenderId: '267960292278',
    projectId: 'ripple-animation-fluttter',
    authDomain: 'ripple-animation-fluttter.firebaseapp.com',
    storageBucket: 'ripple-animation-fluttter.firebasestorage.app',
    measurementId: 'G-E1S502NY5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8kErD7KXvreRNZRZzyhzeWD4jNVCC1yI',
    appId: '1:267960292278:android:a92907e199f8cbf135a717',
    messagingSenderId: '267960292278',
    projectId: 'ripple-animation-fluttter',
    storageBucket: 'ripple-animation-fluttter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOFD56CsAdJHrbyz74CRIZ1JvkQstCQKU',
    appId: '1:267960292278:ios:d9c5945b2263421535a717',
    messagingSenderId: '267960292278',
    projectId: 'ripple-animation-fluttter',
    storageBucket: 'ripple-animation-fluttter.firebasestorage.app',
    iosBundleId: 'com.example.rippleAnimationFlutter',
  );
}
