name: Trigger Codemagic on Push to Main

on:
  push:
    branches:
      - main

jobs:
  trigger-codemagic:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Codemagic Build
        run: |
          curl -X POST https://api.codemagic.io/builds \
            -H "x-auth-token: ${{ secrets.CODEMAGIC_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "appId": "686eb0d80bdc7943b9a1bd21",
              "workflowId": "Default Workflow",
              "branch": "main"
            }'
